test_record.py , 1625865296.082057 , error_code: 1 
